import type { AppRoute } from "../routes";
import type { ModelDescriptor, PoolStats, SignalAnalytics } from "../types";
import { CardHeader, Metric, PageFrame, SplineChart, StatusBadge, compact } from "../components/ui";

export function DashboardPage({ stats, signal, models, operator, onNavigate }: { stats: PoolStats | null; signal: SignalAnalytics | null; models: ModelDescriptor[]; operator: boolean; onNavigate: (path: AppRoute) => void }) {
  const accounts = stats?.accounts ?? [];
  const healthy = accounts.filter(a => a.status === "healthy").length;
  const latest = signal?.hourly.slice(-24) ?? [];
  const availableModels = models.filter(model => model.available_now).length;
  const latestEconomics = signal?.economics.at(-1);
  return <PageFrame kicker={operator ? "Operations overview" : "Workspace overview"} title={operator ? "Gateway overview" : "Good afternoon"} description={operator ? "The current state of routing, capacity, and usage." : "Here is what matters across your gateway right now."} action={<button className="primary-button" onClick={() => onNavigate("/setup")}>Configure a client</button>}>
    <section className="status-banner"><span className="status-symbol">✓</span><div><div className="status-title">Gateway operational <StatusBadge tone="success">Healthy</StatusBadge></div><p>Requests are routing normally across available providers.</p></div><div className="status-facts"><b>{stats ? `${stats.active_accounts} / ${stats.total_accounts}` : "—"}</b><small>Healthy connections</small></div></section>
    <section className="metric-grid"><Metric label={operator ? "Pool requests" : "Your requests"} value={stats ? stats.last_24h_tokens.toLocaleString() : "—"} note="Last 24 hours" /><Metric label="Processed tokens" value={stats ? compact(stats.aggregate.total_billable_tokens) : "—"} note="Measured" /><Metric label="Models available" value={models.length ? `${availableModels} / ${models.length}` : "—"} note="Live catalog" /><Metric label="Provider health" value={`${healthy} / ${accounts.length || "—"}`} note="Current state" /></section>
    <div className="bento-grid"><section className="bento-card chart-card"><CardHeader title="Request activity" subtitle="Rolling activity and comparison" action={<span className="chart-legend"><i className="red-key" />Current <i className="yellow-key" />Prior</span>} /><SplineChart values={latest.map(x => x.request_count)} /></section><section className="bento-card attention-card"><CardHeader title="Attention required" subtitle="Only actionable conditions" /><div className="empty-state"><span className="status-symbol small">✓</span><b>No action required</b><p>There are no active member-facing incidents.</p></div></section><section className="bento-card provider-card"><CardHeader title="Provider health" subtitle="Availability by provider" action={<button className="text-button" onClick={() => onNavigate("/operator/connections")}>View details →</button>} />{accounts.length ? accounts.slice(0, 5).map(a => <div className="provider-summary" key={a.id}><span className="provider-dot" /><b>{a.display_name || a.type}</b><span>{a.status}</span><small>{a.secondary_window_available ? `${a.secondary_window_used_pct.toFixed(0)}% used` : "Capacity unknown"}</small></div>) : <div className="empty-state"><b>Provider data unavailable</b><p>Refresh to retrieve the current connection state.</p></div>}</section><section className="bento-card quick-card"><CardHeader title="Economics" subtitle="Measured gateway value" /><div className="economic-summary"><b>{latestEconomics ? `$${latestEconomics.daily_api_value.toFixed(2)}` : "—"}</b><span>Latest daily API value</span><b>{stats ? `${stats.aggregate.overall_roi.toFixed(1)}x` : "—"}</b><span>Overall ROI</span></div><button className="action-row" onClick={() => onNavigate("/usage")}>View usage & economics <span>→</span></button></section></div>
  </PageFrame>;
}
